### ISSUE TITLE
Error when typings install

### ISSUE THREAD

**Issue by dorianboulch** [Bolisov/typings-gapi#1]
Hello,

I try to import gapi.client and gapi.client.gmail.
So I try `typings install gapi.client --save`
I got this :
`Unable to find "gapi.client" ("npm") in the registry.`

**Comment by Bolisov** [comment]
Hi,

Unfortunately, I did'n publish this to typings repository.
But you can download typings (*.d.ts files) directly from this repo and save to your project.

For example https://github.com/Bolisov/typings-gapi/blob/master/gapi.client/gapi.client.d.ts for base client  definitions and https://github.com/Bolisov/typings-gapi/blob/master/gapi.client.gmail-v1/gapi.client.gmail.d.ts for GMail API.

Please keep in mind, I make this repo long times ago for person use and I didn't update typings in last year. Some things can be broken...

**Comment by dorianboulch** [comment]
No problem, it seems work properly.
I included with this in my typings.json

```json
{
  "globalDependencies": {
    "gapi.client": "github:Bolisov/typings-gapi#963554d9d1970c88208920e3812aed72bf72698b/gapi.client",
    "gapi.client.gmail-v1": "github:Bolisov/typings-gapi#963554d9d1970c88208920e3812aed72bf72698b/gapi.client.gmail-v1"
  }
}
```
